CREATE TABLE IF NOT EXISTS TB_HEROS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NAME_HERO TEXT NOT NULL,
    POWER_HERO TEXT NOT NULL
)

--create
INSERT INTO TB_HEROS (NAME_HERO, POWER_HERO)
VALUES  ('Flash', 'Speed'),
        ('Aquaman', 'Water'),
        ('Batman', 'Money')

--read
SELECT * FROM TB_HEROS WHERE NAME_HERO = 'Flash'

--update
UPDATE TB_HEROS SET NAME_HERO = 'Goku', POWER_HERO = 'God'
WHERE ID = 1

--delete
DELETE FROM TB_HEROS WHERE ID = 2
